import crypto from 'crypto';
import { db } from './db';

const IS_PRODUCTION = process.env.NODE_ENV === 'production';

// --- JWT signing secret -----------------------------------------------------
// Production MUST supply JWT_SECRET via environment/secret manager. We fail
// fast at boot rather than silently signing tokens with a known/guessable
// value. In non-production we generate a random per-boot secret so no fixed
// secret ever lives in source control; this means dev tokens are invalidated
// on every restart, which is an acceptable trade-off for a dev environment.
function resolveJwtSecret(): string {
  const fromEnv = process.env.JWT_SECRET;
  if (fromEnv && fromEnv.trim().length >= 32) {
    return fromEnv;
  }
  if (IS_PRODUCTION) {
    throw new Error(
      '[FATAL] JWT_SECRET is missing or too short (min 32 chars). Refusing to start in production. ' +
      'Set JWT_SECRET to a strong random value (e.g. `openssl rand -hex 32`).'
    );
  }
  console.warn(
    '[auth] JWT_SECRET not set — using an ephemeral random secret for this dev process only. ' +
    'All sessions will be invalidated on restart. Set JWT_SECRET before deploying.'
  );
  return crypto.randomBytes(32).toString('hex');
}

const JWT_SECRET = resolveJwtSecret();

// --- Admin credential --------------------------------------------------------
// Production MUST supply ADMIN_PASSWORD_HASH (format: "<saltHex>:<hashHex>",
// generated by scripts/hash-admin-password.js). We never store or compare a
// plaintext admin passcode. In non-production, if no hash is configured we
// fall back to a well-known dev-only passcode ('gisara2026') so local setup
// keeps working, but this path is hard-blocked in production.
const ADMIN_PASSWORD_HASH = process.env.ADMIN_PASSWORD_HASH || '';
const DEV_ONLY_FALLBACK_PASSCODE = 'gisara2026';

if (IS_PRODUCTION && !ADMIN_PASSWORD_HASH) {
  throw new Error(
    '[FATAL] ADMIN_PASSWORD_HASH is missing. Refusing to start in production. ' +
    'Generate one with `node scripts/hash-admin-password.js "<your-passcode>"` and set it as an env var.'
  );
}

function scryptHash(passcode: string, saltHex: string): string {
  return crypto.scryptSync(passcode, Buffer.from(saltHex, 'hex'), 64).toString('hex');
}

/**
 * Constant-time verification of a passcode against the stored scrypt hash.
 */
function verifyAdminPasscode(passcode: string): boolean {
  if (ADMIN_PASSWORD_HASH) {
    const [saltHex, hashHex] = ADMIN_PASSWORD_HASH.split(':');
    if (!saltHex || !hashHex) return false;
    const candidate = scryptHash(passcode, saltHex);
    const a = Buffer.from(candidate, 'hex');
    const b = Buffer.from(hashHex, 'hex');
    if (a.length !== b.length) return false;
    return crypto.timingSafeEqual(a, b);
  }
  // Dev-only fallback — never reached in production (fail-fast check above).
  return passcode === DEV_ONLY_FALLBACK_PASSCODE;
}

/**
 * Generate a cryptographically signed JWT token (HS256) natively without third-party packages.
 */
export function generateToken(payload: object, expiryMs = 24 * 60 * 60 * 1000): string {
  const header = Buffer.from(JSON.stringify({ alg: 'HS256', typ: 'JWT' })).toString('base64url');
  const exp = Date.now() + expiryMs;
  const body = Buffer.from(JSON.stringify({ ...payload, exp })).toString('base64url');
  
  const hmac = crypto.createHmac('sha256', JWT_SECRET);
  hmac.update(`${header}.${body}`);
  const signature = hmac.digest('base64url');
  
  return `${header}.${body}.${signature}`;
}

/**
 * Verifies a token and returns its decoded payload, or null if invalid/expired.
 */
export function verifyToken(token: string): any | null {
  try {
    const parts = token.split('.');
    if (parts.length !== 3) return null;
    
    const [header, body, signature] = parts;
    
    const hmac = crypto.createHmac('sha256', JWT_SECRET);
    hmac.update(`${header}.${body}`);
    const expectedSignature = hmac.digest('base64url');
    
    if (signature !== expectedSignature) return null;
    
    const payload = JSON.parse(Buffer.from(body, 'base64url').toString('utf8'));
    if (Date.now() > payload.exp) {
      return null; // Expired
    }
    
    return payload;
  } catch {
    return null;
  }
}

/**
 * Parse incoming HTTP Cookie headers into a key-value map
 */
export function parseCookies(req: any): Record<string, string> {
  const list: Record<string, string> = {};
  const rc = req.headers?.cookie;
  if (rc) {
    rc.split(';').forEach((cookie: string) => {
      const parts = cookie.split('=');
      if (parts.length >= 2) {
        list[parts[0].trim()] = decodeURIComponent(parts.slice(1).join('=').trim());
      }
    });
  }
  return list;
}

/**
 * Sets a secure HttpOnly cookie for the authenticated token
 */
export function setAuthCookie(res: any, token: string, expiryMs = 24 * 60 * 60 * 1000): void {
  const maxAgeSec = Math.floor(expiryMs / 1000);
  const isSecure = process.env.NODE_ENV === 'production' || process.env.HTTPS === 'true';
  const cookieOptions = [
    `gisara_token=${encodeURIComponent(token)}`,
    'Path=/',
    'HttpOnly',
    'SameSite=Lax',
    `Max-Age=${maxAgeSec}`
  ];
  if (isSecure) {
    cookieOptions.push('Secure');
  }
  res.setHeader('Set-Cookie', cookieOptions.join('; '));
}

/**
 * Clears the HttpOnly authentication cookie
 */
export function clearAuthCookie(res: any): void {
  res.setHeader('Set-Cookie', 'gisara_token=; Path=/; HttpOnly; SameSite=Lax; Expires=Thu, 01 Jan 1970 00:00:00 GMT; Max-Age=0');
}

/**
 * Express Authentication middleware to populate req.user from JWT Bearer token or HttpOnly Cookie
 */
export function authMiddleware(req: any, res: any, next: any) {
  // Cookie-only sessions: the credential lives in an HttpOnly cookie that page
  // scripts cannot read. Bearer headers are intentionally NOT accepted, so a token
  // that leaks (logs, storage, XSS) cannot be replayed from another context.
  let token: string | null = null;
  const cookies = parseCookies(req);
  if (cookies.gisara_token) {
    token = cookies.gisara_token;
  }

  if (token) {
    req.user = verifyToken(token);
  } else {
    req.user = null;
  }

  next();
}

/**
 * Strict authentication guard for registered users
 */
export function requireAuth(req: any, res: any, next: any) {
  if (!req.user) {
    return res.status(401).json({ success: false, message: 'لطفاً ابتدا وارد حساب کاربری خود شوید.' });
  }
  next();
}

/**
 * Strict route guard for Administrator actions
 */
export function requireAdmin(req: any, res: any, next: any) {
  if (!req.user || req.user.role !== 'ADMIN') {
    return res.status(403).json({ success: false, message: 'خطای عدم دسترسی: این عملیات نیاز به سطح دسترسی مدیریت دارد.' });
  }
  next();
}

/**
 * Generates and saves a 6-digit OTP code for a given mobile number.
 * Uses a CSPRNG (crypto.randomInt), never Math.random.
 */
export function generateOTP(mobile: string): string {
  const code = crypto.randomInt(100000, 1000000).toString();
  const expiresAt = Date.now() + 2 * 60 * 1000; // 2 minutes validation

  // Clean old/existing OTPs for this mobile
  db.otps = db.otps.filter(o => o.mobile !== mobile && Date.now() < o.expiresAt);

  // Add new OTP
  const updatedOtps = [...db.otps, { mobile, code, expiresAt, attempts: 0 }];
  db.otps = updatedOtps;

  // Never log the raw code in production — only in local dev for debugging.
  if (!IS_PRODUCTION) {
    console.log(`[OTP Engine][dev-only] Generated code ${code} for mobile ${mobile}`);
  }
  return code;
}

/**
 * Verifies an OTP code for a mobile number. Returns boolean indicating success.
 */
export function verifyOTP(mobile: string, code: string): boolean {
  const now = Date.now();
  const entry = db.otps.find(o => o.mobile === mobile && now < o.expiresAt);
  
  if (!entry) return false;
  
  if (entry.attempts >= 3) {
    db.otps = db.otps.filter(o => o.mobile !== mobile); // Locked out / deleted
    return false;
  }
  
  if (entry.code !== code) {
    entry.attempts++;
    db.otps = [...db.otps]; // Trigger write to persistence
    return false;
  }
  
  // Verification success, clean OTP
  db.otps = db.otps.filter(o => o.mobile !== mobile);
  return true;
}

/**
 * Verifies admin passcode and returns token if correct
 */
export function authenticateAdmin(passcode: string): string | null {
  if (verifyAdminPasscode(passcode)) {
    return generateToken({
      role: 'ADMIN',
      name: 'مدیریت گیسآرا',
      mobile: '09000000000'
    }, 12 * 60 * 60 * 1000); // Admin session lasts 12 hours
  }
  return null;
}
