import crypto from 'crypto';
import { getOrCreateUser } from './users';

const IS_PRODUCTION = process.env.NODE_ENV === 'production';

// --- JWT signing secret -----------------------------------------------------
// Production MUST supply JWT_SECRET via environment/secret manager. We fail
// fast at boot rather than silently signing tokens with a known/guessable
// value. In non-production we generate a random per-boot secret so no fixed
// secret ever lives in source control; this means dev tokens are invalidated
// on every restart, which is an acceptable trade-off for a dev environment.
function resolveJwtSecret(): string {
  const fromEnv = process.env.JWT_SECRET;
  if (fromEnv && fromEnv.trim().length >= 32) {
    return fromEnv;
  }
  if (IS_PRODUCTION) {
    throw new Error(
      '[FATAL] JWT_SECRET is missing or too short (min 32 chars). Refusing to start in production. ' +
      'Set JWT_SECRET to a strong random value (e.g. `openssl rand -hex 32`).'
    );
  }
  console.warn(
    '[auth] JWT_SECRET not set — using an ephemeral random secret for this dev process only. ' +
    'All sessions will be invalidated on restart. Set JWT_SECRET before deploying.'
  );
  return crypto.randomBytes(32).toString('hex');
}

const JWT_SECRET = resolveJwtSecret();

// --- Admin credential --------------------------------------------------------
// Production MUST supply ADMIN_PASSWORD_HASH (format: "<saltHex>:<hashHex>",
// generated by scripts/hash-admin-password.js). We never store or compare a
// plaintext admin passcode. In non-production, if no hash is configured we
// fall back to a well-known dev-only passcode ('gisara2026') so local setup
// keeps working, but this path is hard-blocked in production.
const ADMIN_PASSWORD_HASH = process.env.ADMIN_PASSWORD_HASH || '';
const DEV_ONLY_FALLBACK_PASSCODE = 'gisara2026';
const DEV_AUTH_ALLOWED = !IS_PRODUCTION && process.env.ALLOW_DEV_AUTH === '1';
if (DEV_AUTH_ALLOWED && !ADMIN_PASSWORD_HASH) {
  console.warn('[auth] ALLOW_DEV_AUTH=1: the well-known development admin passcode is ENABLED. Never use this setting on a public server.');
}

if (IS_PRODUCTION && !ADMIN_PASSWORD_HASH) {
  throw new Error(
    '[FATAL] ADMIN_PASSWORD_HASH is missing. Refusing to start in production. ' +
    'Generate one with `node scripts/hash-admin-password.js "<your-passcode>"` and set it as an env var.'
  );
}

function scryptHash(passcode: string, saltHex: string): string {
  return crypto.scryptSync(passcode, Buffer.from(saltHex, 'hex'), 64).toString('hex');
}

/**
 * Constant-time verification of a passcode against the stored scrypt hash.
 */
function verifyAdminPasscode(passcode: string): boolean {
  if (ADMIN_PASSWORD_HASH) {
    const [saltHex, hashHex] = ADMIN_PASSWORD_HASH.split(':');
    if (!saltHex || !hashHex) return false;
    const candidate = scryptHash(passcode, saltHex);
    const a = Buffer.from(candidate, 'hex');
    const b = Buffer.from(hashHex, 'hex');
    if (a.length !== b.length) return false;
    return crypto.timingSafeEqual(a, b);
  }
  // Dev-only fallback: needs an EXPLICIT opt-in (ALLOW_DEV_AUTH=1, set by `npm run dev`) and is impossible in
  // production. A staging server that merely forgot NODE_ENV therefore no longer accepts the well-known passcode.
  if (!DEV_AUTH_ALLOWED) return false;
  return passcode === DEV_ONLY_FALLBACK_PASSCODE;
}

/**
 * Generate a cryptographically signed JWT token (HS256) natively without third-party packages.
 */
export function generateToken(payload: object, expiryMs = 24 * 60 * 60 * 1000): string {
  const header = Buffer.from(JSON.stringify({ alg: 'HS256', typ: 'JWT' })).toString('base64url');
  const exp = Date.now() + expiryMs;
  const body = Buffer.from(JSON.stringify({ ...payload, exp })).toString('base64url');
  
  const hmac = crypto.createHmac('sha256', JWT_SECRET);
  hmac.update(`${header}.${body}`);
  const signature = hmac.digest('base64url');
  
  return `${header}.${body}.${signature}`;
}

/**
 * Verifies a token and returns its decoded payload, or null if invalid/expired.
 */
export function verifyToken(token: string): any | null {
  try {
    const parts = token.split('.');
    if (parts.length !== 3) return null;
    
    const [header, body, signature] = parts;
    
    const hmac = crypto.createHmac('sha256', JWT_SECRET);
    hmac.update(`${header}.${body}`);
    const expectedSignature = hmac.digest('base64url');
    
    const given = Buffer.from(signature);
    const wanted = Buffer.from(expectedSignature);
    if (given.length !== wanted.length || !crypto.timingSafeEqual(given, wanted)) return null;
    
    const payload = JSON.parse(Buffer.from(body, 'base64url').toString('utf8'));
    if (Date.now() > payload.exp) {
      return null; // Expired
    }
    
    return payload;
  } catch {
    return null;
  }
}

/**
 * Parse incoming HTTP Cookie headers into a key-value map
 */
export function parseCookies(req: any): Record<string, string> {
  const list: Record<string, string> = {};
  const rc = req.headers?.cookie;
  if (rc) {
    rc.split(';').forEach((cookie: string) => {
      const parts = cookie.split('=');
      if (parts.length >= 2) {
        list[parts[0].trim()] = decodeURIComponent(parts.slice(1).join('=').trim());
      }
    });
  }
  return list;
}

// Customers and administrators use SEPARATE cookies so that signing in as a customer in the same browser
// never destroys an admin session (and vice-versa).
export const USER_COOKIE = 'gisara_token';
export const ADMIN_COOKIE = 'gisara_admin';

/**
 * Sets a secure HttpOnly cookie for the authenticated token
 */
export function setAuthCookie(res: any, token: string, expiryMs = 24 * 60 * 60 * 1000, cookieName: string = USER_COOKIE): void {
  const maxAgeSec = Math.floor(expiryMs / 1000);
  const isSecure = process.env.NODE_ENV === 'production' || process.env.HTTPS === 'true';
  const cookieOptions = [
    `${cookieName}=${encodeURIComponent(token)}`,
    'Path=/',
    'HttpOnly',
    'SameSite=Lax',
    `Max-Age=${maxAgeSec}`
  ];
  if (isSecure) {
    cookieOptions.push('Secure');
  }
  res.setHeader('Set-Cookie', cookieOptions.join('; '));
}

/**
 * Clears an HttpOnly authentication cookie
 */
export function clearAuthCookie(res: any, cookieName: string = USER_COOKIE): void {
  res.setHeader('Set-Cookie', `${cookieName}=; Path=/; HttpOnly; SameSite=Lax; Expires=Thu, 01 Jan 1970 00:00:00 GMT; Max-Age=0`);
}

/**
 * Express Authentication middleware. Populates:
 *   req.admin - a valid administrator session (admin cookie), or null
 *   req.user  - the acting identity: the signed-in customer, or the administrator when there is no customer
 *               session or the admin console explicitly asks for it (X-Admin-Context: 1).
 * Bearer headers are intentionally NOT accepted: credentials live only in HttpOnly cookies.
 */
export function authMiddleware(req: any, res: any, next: any) {
  const cookies = parseCookies(req);

  const adminPayload = cookies[ADMIN_COOKIE] ? verifyToken(cookies[ADMIN_COOKIE]) : null;
  req.admin = adminPayload && adminPayload.role === 'ADMIN' ? adminPayload : null;

  const userPayload = cookies[USER_COOKIE] ? verifyToken(cookies[USER_COOKIE]) : null;
  let user: any = null;
  if (userPayload && userPayload.role === 'USER' && typeof userPayload.mobile === 'string') {
    // Identity is read from the user store on every request, so a renamed account shows its new name at once.
    const record = getOrCreateUser(userPayload.mobile);
    user = { role: 'USER', mobile: record.mobile, name: record.name, userCode: record.userCode, avatar: record.avatar };
  }

  const wantsAdmin = req.headers?.['x-admin-context'] === '1';
  if (req.admin && (!user || wantsAdmin)) {
    user = { role: 'ADMIN', name: req.admin.name, mobile: req.admin.mobile };
  }

  req.user = user;
  next();
}

/**
 * Strict authentication guard for registered users
 */
export function requireAuth(req: any, res: any, next: any) {
  if (!req.user) {
    return res.status(401).json({ success: false, message: 'لطفاً ابتدا وارد حساب کاربری خود شوید.' });
  }
  next();
}

/**
 * Strict route guard for Administrator actions
 */
export function requireAdmin(req: any, res: any, next: any) {
  if (!req.admin) {
    return res.status(403).json({ success: false, message: 'خطای عدم دسترسی: این عملیات نیاز به سطح دسترسی مدیریت دارد.' });
  }
  // Admin routes always act as the administrator, even when a customer session exists in the same browser.
  req.user = { role: 'ADMIN', name: req.admin.name, mobile: req.admin.mobile };
  next();
}

// --- One-time passcodes -----------------------------------------------------
// Held in MEMORY only (never written to db.json / backups) and stored as an HMAC, so neither a leaked
// database file nor a backup export can reveal a valid code.
const OTP_TTL_MS = 2 * 60 * 1000;
const OTP_COOLDOWN_MS = 60 * 1000;
const OTP_MAX_ATTEMPTS = 5;
const OTP_HOURLY_CAP = 6;
const OTP_SECRET = crypto.createHmac('sha256', JWT_SECRET).update('otp-v1').digest();

interface OtpEntry { hash: Buffer; expiresAt: number; attempts: number }
const otpStore = new Map<string, OtpEntry>();
const otpSendLog = new Map<string, number[]>();

const hashCode = (mobile: string, code: string) => crypto.createHmac('sha256', OTP_SECRET).update(`${mobile}:${code}`).digest();

function pruneOtps(now: number) {
  for (const [m, e] of otpStore) if (now > e.expiresAt + OTP_TTL_MS) otpStore.delete(m);
  for (const [m, list] of otpSendLog) {
    const recent = list.filter((t) => now - t < 60 * 60 * 1000);
    if (recent.length === 0) otpSendLog.delete(m);
    else otpSendLog.set(m, recent);
  }
}

/** Per-number throttle (the per-IP limiter alone does not stop someone flooding ONE phone with SMS). */
export function checkOtpRequestAllowed(mobile: string): { ok: true } | { ok: false; retryAfterSec: number; reason: 'cooldown' | 'hourly' } {
  const now = Date.now();
  pruneOtps(now);
  const sent = otpSendLog.get(mobile) || [];
  const last = sent[sent.length - 1];
  if (last && now - last < OTP_COOLDOWN_MS) {
    return { ok: false, reason: 'cooldown', retryAfterSec: Math.ceil((OTP_COOLDOWN_MS - (now - last)) / 1000) };
  }
  if (sent.length >= OTP_HOURLY_CAP) {
    return { ok: false, reason: 'hourly', retryAfterSec: Math.ceil((60 * 60 * 1000 - (now - sent[0])) / 1000) };
  }
  return { ok: true };
}

export const OTP_COOLDOWN_SEC = OTP_COOLDOWN_MS / 1000;
export const OTP_TTL_SEC = OTP_TTL_MS / 1000;

/**
 * Generates a 6-digit code (CSPRNG) for a mobile number and remembers only its HMAC.
 */
export function generateOTP(mobile: string): string {
  const code = crypto.randomInt(100000, 1000000).toString();
  const now = Date.now();
  otpStore.set(mobile, { hash: hashCode(mobile, code), expiresAt: now + OTP_TTL_MS, attempts: 0 });
  otpSendLog.set(mobile, [...(otpSendLog.get(mobile) || []), now]);

  // Never log the raw code in production — only in local dev for debugging.
  if (!IS_PRODUCTION) {
    console.log(`[OTP Engine][dev-only] Generated code ${code} for mobile ${mobile}`);
  }
  return code;
}

/** Forget a code whose SMS could not be delivered, and do not count that attempt against the person. */
export function discardOTP(mobile: string): void {
  otpStore.delete(mobile);
  const log = otpSendLog.get(mobile) || [];
  otpSendLog.set(mobile, log.slice(0, -1));
}

export type OtpVerifyResult =
  | { ok: true }
  | { ok: false; reason: 'expired' | 'invalid' | 'locked'; attemptsLeft?: number };

/**
 * Verifies a code. Constant-time comparison; the code is single-use and locks after too many wrong tries.
 */
export function verifyOTP(mobile: string, code: string): OtpVerifyResult {
  const now = Date.now();
  const entry = otpStore.get(mobile);
  if (!entry || now > entry.expiresAt) {
    otpStore.delete(mobile);
    return { ok: false, reason: 'expired' };
  }
  if (entry.attempts >= OTP_MAX_ATTEMPTS) {
    otpStore.delete(mobile);
    return { ok: false, reason: 'locked' };
  }
  const candidate = hashCode(mobile, code);
  if (candidate.length !== entry.hash.length || !crypto.timingSafeEqual(candidate, entry.hash)) {
    entry.attempts++;
    if (entry.attempts >= OTP_MAX_ATTEMPTS) {
      otpStore.delete(mobile);
      return { ok: false, reason: 'locked' };
    }
    return { ok: false, reason: 'invalid', attemptsLeft: OTP_MAX_ATTEMPTS - entry.attempts };
  }
  otpStore.delete(mobile);
  return { ok: true };
}

/** Test hook: wipes in-memory OTP state. */
export function __resetOtpStateForTests() {
  otpStore.clear();
  otpSendLog.clear();
}

/**
 * Verifies admin passcode and returns token if correct
 */
export function authenticateAdmin(passcode: string): string | null {
  if (verifyAdminPasscode(passcode)) {
    return generateToken({
      role: 'ADMIN',
      name: 'مدیریت گیسآرا',
      mobile: '09000000000'
    }, 12 * 60 * 60 * 1000); // Admin session lasts 12 hours
  }
  return null;
}
